services:
  app:
    build: .
    container_name: canvas-smith
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      ENVIRONMENT: development
      SERVE_FRONTEND: "true"
      STATIC_DIR: static
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8000/health', timeout=10)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
